name: Workflow Filters and Activities

on:
    workflow_dispatch:
    # schedule:
    #     - cron: "*/59 * * * *"
    push:
        branches:
            - main
            - '!feature/*'    # ignoring pushing to any branch name starting with feature using !
        # branches-ignore:

            # - feature/*
            # - test/**    # test/ui/index, test/cehckout/payment/
    pull_request:
        types:
            - opened
            - closed
        paths-ignore:     # workflow will only run when a pull request that includes a change on any file other than README.md
            - README.md
        branches:
            - main.      # configure your workflow to only run on pull requests that target specific branches
    

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - run: echo this workdflow/job/step is executed for event type - ${{ github.event_name }}